#!/usr/bin/env python3
"""
Backward-compatible facade for the yard planning package.

External callers can keep importing symbols from `yardplan` and calling
`run_plan()` as before, while the implementation now lives in `yardplan_core`.
"""

from yardplan_core import (
    AllocationEngine,
    AllocationGroup,
    AreaAssignment,
    AreaWorkloadProvider,
    AreaWorkloadSnapshot,
    AreaResourceState,
    AreaScoringStrategy,
    Bay,
    BayColumnAllocation,
    BusinessType,
    ColumnDemandConverter,
    ConstraintChecker,
    Container,
    ContainerSize,
    ContainerType,
    DEFAULT_EXPORT_GROUP_KEYS,
    DEFAULT_IMPORT_GROUP_KEYS,
    DefaultAreaScoringStrategy,
    FlowType,
    GroupKeyFunc,
    GroupingConfig,
    GroupingEngine,
    LargeBayPair,
    MAX_SPLITS_PER_GROUP,
    MAX_TIERS_PER_COLUMN,
    MIN_COLUMNS_PER_SPLIT,
    PlannerMode,
    PlanningResult,
    PlacementPreview,
    ResultFormatter,
    RollingWindow,
    RollingWindowPlanner,
    SimulatedAreaWorkloadProvider,
    Stage1LNSConfig,
    Stage1YardAreaAssigner,
    Stage2BayAllocator,
    TOSAreaWorkloadProvider,
    TOSLoader,
    TimeStep,
    Vessel,
    WorkloadEstimationConfig,
    WeightClass,
    YardArea,
    YardFlow,
    YardVisualizationConfig,
    YardVisualizer,
    YardPlanner,
    YardSpaceAdapter,
    _DATA_DIR,
    logger,
    run_plan,
    save_yard_visualization,
    plot_yard,
    build_yard_layout,
)

__all__ = [
    "_DATA_DIR",
    "logger",
    "MAX_TIERS_PER_COLUMN",
    "MAX_SPLITS_PER_GROUP",
    "MIN_COLUMNS_PER_SPLIT",
    "BusinessType",
    "ContainerSize",
    "ContainerType",
    "WeightClass",
    "PlannerMode",
    "FlowType",
    "Container",
    "Bay",
    "LargeBayPair",
    "YardArea",
    "Vessel",
    "YardFlow",
    "YardVisualizationConfig",
    "YardVisualizer",
    "AllocationGroup",
    "AreaAssignment",
    "BayColumnAllocation",
    "PlanningResult",
    "ColumnDemandConverter",
    "GroupKeyFunc",
    "DEFAULT_EXPORT_GROUP_KEYS",
    "DEFAULT_IMPORT_GROUP_KEYS",
    "GroupingConfig",
    "GroupingEngine",
    "TimeStep",
    "RollingWindow",
    "RollingWindowPlanner",
    "ConstraintChecker",
    "PlacementPreview",
    "AreaResourceState",
    "Stage1LNSConfig",
    "AreaScoringStrategy",
    "DefaultAreaScoringStrategy",
    "Stage1YardAreaAssigner",
    "Stage2BayAllocator",
    "AllocationEngine",
    "AreaWorkloadProvider",
    "AreaWorkloadSnapshot",
    "SimulatedAreaWorkloadProvider",
    "TOSAreaWorkloadProvider",
    "WorkloadEstimationConfig",
    "YardSpaceAdapter",
    "TOSLoader",
    "ResultFormatter",
    "YardPlanner",
    "run_plan",
    "save_yard_visualization",
    "plot_yard",
    "build_yard_layout",
]


if __name__ == "__main__":
    from datetime import datetime

    # 航次 YH25004（远航888）：ETA 2025-12-21 16:00，ETD 2025-12-25 16:00
    run_plan(
        line_keys=[15525576],
        type=1,
        save_visualization=True,
        plan_start_time=datetime(2025, 12, 21, 0, 0, 0),
        plan_end_time=datetime(2025, 12, 26, 0, 0, 0),
    )
